lex_tokens = {
    "sunekeh": "if",
    "mohopah": ">",
    "mohndaw": "<",
    "wonel": "print",
    ":": ":",
    "kon": "else",
    "puru": "for",
    "bunekasi": "in",
    "feka": "while",
    "defal": "def",
    "dama": "break",
    "mohemak": "==",
    "emutak": "!=",
    "dugal": "input",
    "yoka": "+",
    "deloh": "return",
    "waanyi": "-",
    "sedoh": "/",
    "ful": "*",
    "degah": "True",
    "dudegah": "False",
}

numbers = {
    "neen": 0,
    "bena": 1,
    "nyaar": 2,
    "nyet": 3,
    "nyenent": 4,
    "jurom": 5,
    "juromBen": 6,
    "juromNyaar": 7,
    "juromNyet": 8,
    "juromNyenent": 9,
    "fuk": 10,
}